// AUTO-GENERATED by `node dist/lzx-check.js --write-lfc-dts` from the
// compiler's oracle schema (schema-types.ts) and the LFC source AST
// (lfc-reflect.ts). Do not edit by hand.

declare class LzEventable {
  _events: any[];
  ondestroy: any;
  customSetters: any;
  destroy(): any;
  removeDelegates(): any;
  childOf(node?: any, ignore?: any): any;
}
declare class LzDeclaredEvent { ready: boolean; sendEvent(value?: any): void; }

declare class LzNode extends LzEventable {
  constructor(parent?: LzNode, attrs?: Record<string, any>);
  classroot: LzNode;
  cloneManager: string;
  datapath: string;
  defaultplacement: string;
  id: string;
  ignoreplacement: boolean;
  immediateparent: LzNode;
  inited: boolean;
  initstage: string;
  name: string;
  nodeLevel: number;
  options: any;
  parent: LzNode;
  placement: string;
  styleclass: string;
  subnodes: LzNode[];
  transition: string;
  onconstruct: LzDeclaredEvent;
  ondata: LzDeclaredEvent;
  oninit: LzDeclaredEvent;
  setAttribute<K extends keyof this & string>(name: K, value: this[K]): void;
  destroy(): void;
  animate(prop: string, to: number, duration: number, isRelative?: boolean | null, moreargs?: Record<string, any> | null): any;
  static tagname: any;
  static attributes: any;
  classChildren: any[];
  animators: any[];
  _instanceAttrs: any;
  _instanceChildren: any[];
  clonenumber: any;
  onclonenumber: any;
  isinited: any;
  oninited: any;
  dependencies: any;
  onstyleclass: LzDeclaredEventClass;
  static _ignoreAttribute: any;
  data: any;
  ontransition: any;
  static mergeAttributes(attrs?: any, dattrs?: any): any;
  static mergeChildren(children?: any, superclasschildren?: any): any;
  construct(parent?: any, args?: any): any;
  init(): any;
  completeInstantiation(): any;
  createChildren(carr?: any): any;
  makeChild(e?: any, async?: any): any;
  dataBindAttribute(attr?: any, path?: any, type?: any): any;
  applyConstraint(attribute?: any, constraint?: any, dependencies?: any): any;
  applyConstraintMethod(constraintMethodName?: any, dependencies?: any): any;
  applyConstraintExpr(expr?: LzOnceExpr): any;
  releaseConstraint(attr?: string): any;
  releaseConstraintMethod(constraintMethodName?: any): any;
  setDatapath(dp?: any): any;
  setData(data?: any, ignore?: any): any;
  applyData(data?: any): any;
  updateData(): any;
  setSelected(sel?: any): any;
  getOption(key?: any): any;
  setOption(key?: any, val?: any): any;
  determinePlacement(aSub?: any, placement?: any, args?: any): any;
  searchImmediateSubnodes(prop?: any, val?: any): any;
  searchSubnodes(prop?: any, val?: any): any;
  searchParents(prop?: any): any;
  searchParentAttrs(proplist?: any): any;
  getUID(): any;
  childOf(node?: any, ignore?: any): any;
  toString(): any;
  getDebugIdentification(): any;
  nodePath(node?: LzNode, limit?: any): any;
  acceptTypeValue(type?: any, value?: any, node?: LzNode, attribute?: string): any;
  acceptAttribute(name?: any, type?: any, value?: any): any;
  presentTypeValue(type?: any, value?: any, node?: LzNode, attribute?: string): any;
  presentAttribute(name?: any, type?: any): any;
}

declare class LzAnimatorgroup extends LzNode {
  attribute: string;
  duration: number;
  from: number;
  indirect: boolean;
  isactive: boolean;
  motion: string;
  paused: boolean;
  process: string;
  relative: boolean;
  repeat: number;
  start: boolean;
  started: boolean;
  target: any;
  to: number;
  onrepeat: LzDeclaredEvent;
  onstart: LzDeclaredEvent;
  onstop: LzDeclaredEvent;
  static tagname: string;
  static attributes: any;
  updateDel: LzDelegate;
  crepeat: number;
  startTime: number;
  actAnim: any[];
  notstarted: boolean;
  needsrestart: boolean;
  onstarted: LzDeclaredEventClass;
  onduration: LzDeclaredEventClass;
  onpaused: LzDeclaredEventClass;
  ontarget: LzDeclaredEventClass;
  animatorProps: any;
  construct(parent?: any, args?: any): any;
  init(): any;
  doStart(): any;
  prepareStart(): void;
  resetAnimator(): void;
  update(time?: number): boolean;
  pause(dop?: any): any;
  stop(): any;
  checkRepeat(): boolean;
  destroy(): any;
  toString(): any;
}

declare class LzAnimator extends LzAnimatorgroup {
  static tagname: string;
  static attributes: any;
  calcMethod: (...args: any[]) => any;
  currentValue: number;
  doBegin: boolean;
  beginPoleDelta: number;
  endPoleDelta: number;
  primary_K: number;
  origto: number;
  beginPole: number;
  endPole: number;
  counterkey: string;
  onattribute: LzDeclaredEventClass;
  construct(parent?: any, args?: any): any;
  calcControlValues(): void;
  doStart(): any;
  updateCounter(delta?: number): number;
  prepareStart(): void;
  resetAnimator(): void;
  beginAnimator(time?: number): void;
  stop(): any;
  calcNextValue(timeDifference?: number): number;
  calcNextValueLinear(timeDifference?: number): number;
  update(time?: number): boolean;
  toString(): any;
}

declare class LzContextmenu extends LzNode {
  onmenuopen: LzDeclaredEvent;
  static tagname: string;
  static attributes: any;
  kernel: LzContextMenuKernel;
  items: any[];
  construct(parent?: any, args?: any): any;
  init(): any;
  setDelegate(delegate?: LzDelegate): void;
  addItem(item?: LzContextMenuItem): void;
  hideBuiltInItems(): void;
  showBuiltInItems(): void;
  clearItems(): void;
  getItems(): any[];
  makeMenuItem(title?: string, delegate?: any): LzContextMenuItem;
}

declare class LzContextmenuitem extends LzNode {
  delegate: any;
  caption: string;
  enabled: boolean;
  separatorbefore: boolean;
  visible: boolean;
  onselect: LzDeclaredEvent;
  static tagname: string;
  static attributes: any;
  kernel: LzContextMenuItemKernel;
  construct(parent?: any, args?: any): any;
  setDelegate(delegate?: any): void;
  setCaption(caption?: string): void;
  getCaption(): string;
  setEnabled(val?: boolean): void;
  setSeparatorBefore(val?: boolean): void;
  setVisible(val?: boolean): void;
}

declare class LzDatapointer extends LzNode {
  context: string;
  p: string;
  rerunxpath: boolean;
  xpath: string;
  onerror: LzDeclaredEvent;
  ontimeout: LzDeclaredEvent;
  static tagname: string;
  static attributes: any;
  parsedPath: LzParsedPath;
  errorDel: LzDelegate;
  timeoutDel: LzDelegate;
  onp: LzDeclaredEventClass;
  onDocumentChange: LzDeclaredEventClass;
  onrerunxpath: LzDeclaredEventClass;
  static ppcache: any;
  static pathSymbols: any;
  gotError(ds?: LzDataset): void;
  gotTimeout(ds?: LzDataset): void;
  xpathQuery(p?: any): any;
  setPointer(p?: any): boolean;
  getDataset(): LzDataset;
  setXPath(p?: string): boolean;
  runXPath(): boolean;
  isValid(): boolean;
  parsePath(pa?: any): LzParsedPath;
  getLocalDataContext(pp?: any[]): LzDataset;
  getContext(chgpkg?: any): any;
  nodeByName(name?: string, range?: any[], p?: any): any[];
  dupePointer(): LzDatapointer;
  selectNext(amnt?: any): boolean;
  selectPrev(amnt?: any): boolean;
  selectChild(amnt?: any): boolean;
  selectParent(amnt?: any): boolean;
  selectNextParent(): boolean;
  getNodeOffset(): any;
  getXPathIndex(): number;
  getNodeType(): any;
  getNodeName(): string;
  setNodeName(name?: string): void;
  getNodeAttributes(): any;
  getNodeAttribute(name?: string): string;
  setNodeAttribute(name?: string, val?: string): void;
  deleteNodeAttribute(name?: string): void;
  getNodeText(): string;
  setNodeText(val?: string): void;
  getNodeCount(): number;
  addNode(name?: string, text?: string, attrs?: any): LzDataElement;
  deleteNode(): any;
  sendDataChange(chgpkg?: any): void;
  comparePointer(ptr?: LzDatapointer): boolean;
  addNodeFromPointer(dp?: LzDatapointer): LzDatapointer;
  setFromPointer(dp?: LzDatapointer): void;
  makeRootNode(): LzDataElement;
  finishRootNode(n?: any): any;
  makeElementNode(attrs?: any, name?: any, par?: any): LzDataElement;
  makeTextNode(text?: any, par?: any): LzDataText;
  serialize(): string;
  setDataContext(dc?: any, ignore?: boolean): void;
  destroy(): any;
}

declare class LzDatapath extends LzDatapointer {
  axis: string;
  pooling: boolean;
  replication: string;
  sortorder: string;
  sortpath: string;
  spacing: number;
  static tagname: string;
  static attributes: any;
  datacontrolsvisibility: boolean;
  storednodes: any[];
  sel: boolean;
  setOrder(xpath?: string, comparator?: any): void;
  setComparator(comparator?: any): void;
  construct(v?: any, args?: any): any;
  setNodes(nodes?: any[]): void;
  setDataContext(dc?: any, implicit?: boolean): void;
  destroy(): any;
  updateData(): any;
  toString(): any;
  setClonePointer(p?: any): void;
  setSelected(torf?: any): any;
}

declare class LzDataset extends LzNode {
  acceptencodings: boolean;
  autorequest: boolean;
  cacheable: boolean;
  clientcacheable: boolean;
  dataprovider: any;
  getresponseheaders: boolean;
  multirequest: boolean;
  nsprefix: boolean;
  params: string;
  postbody: string;
  proxied: boolean;
  proxyurl: string;
  querystring: string;
  querytype: string;
  rawdata: string;
  request: boolean;
  secureport: number;
  src: string;
  timeout: number;
  trimwhitespace: boolean;
  type: string;
  queuerequests: boolean;
  datafromchild: boolean;
  onerror: LzDeclaredEvent;
  ontimeout: LzDeclaredEvent;
  static tagname: any;
  static attributes: any;
  static slashPat: string;
  dataRequest: LzHTTPDataRequest;
  dataRequestClass: any;
  dsloadDel: LzDelegate;
  errorstring: string;
  reqOnInitDel: LzDelegate;
  headers: LzParam;
  responseheaders: LzParam;
  oncanvas: boolean;
  isProxied(): boolean;
  construct(parent?: any, args?: any): any;
  destroy(): any;
  getErrorString(): string;
  getLoadTime(): number;
  getSrc(): string;
  getQueryString(): string;
  getParams(): LzParam;
  gotError(e?: string): void;
  gotTimeout(): void;
  getContext(chgpkg?: any): any;
  getDataset(): LzDataset;
  getPointer(): LzDatapointer;
  setQueryString(s?: any): void;
  setQueryParam(key?: string, val?: string): void;
  setQueryParams(obj?: any): void;
  setSrc(src?: string): void;
  setProxyRequests(val?: string): void;
  setRequest(b?: boolean): void;
  setAutorequest(b?: boolean): void;
  setPostBody(str?: string): void;
  setQueryType(reqtype?: string): void;
  setInitialData(d?: string): void;
  static queryStringToTable(query?: string): any;
  abort(): void;
  doRequest(ignore?: any): void;
  handleDataResponse(datareq?: LzHTTPDataRequest): void;
  setHeader(k?: string, val?: string): void;
  getRequestHeaderParams(): LzParam;
  clearRequestHeaderParams(): void;
  getResponseHeader(name?: string): any;
  getAllResponseHeaders(): LzParam;
  toString(): any;
}

declare class LzState extends LzNode {
  applied: boolean;
  pooling: boolean;
  onapply: LzDeclaredEvent;
  onremove: LzDeclaredEvent;
  static tagname: any;
  static attributes: any;
  heldArgs: any;
  releasedconstraints: any;
  appliedChildren: any;
  applyOnInit: boolean;
  onapplied: LzDeclaredEventClass;
  static events: any;
  asyncnew: any;
  subh: any;
  init(): any;
  createChildren(carr?: any): any;
  apply(): any;
  remove(): any;
  destroy(): any;
}

declare class LzView extends LzNode {
  aaactive: boolean;
  aadescription: string;
  aaname: string;
  aasilent: boolean;
  aatabindex: number;
  align: string;
  backgroundrepeat: string;
  bgcolor: string | number;
  cachebitmap: boolean;
  capabilities: string;
  clickable: boolean;
  clickregion: string;
  clip: boolean;
  colortransform: any;
  context: any;
  contextmenu: string;
  cornerradius: string;
  cursor: string;
  fgcolor: string | number;
  focusable: boolean;
  focustrap: boolean;
  font: string;
  fontsize: number;
  fontstyle: string;
  frame: number;
  framesloadratio: number;
  hassetheight: boolean;
  hassetwidth: boolean;
  height: number;
  layout: any;
  loadratio: number;
  mask: string;
  opacity: number;
  pixellock: boolean;
  playing: boolean;
  resource: string;
  resourceheight: number;
  resourcewidth: number;
  rotation: number;
  shadowangle: number;
  shadowblurradius: number;
  shadowcolor: string | number;
  shadowdistance: number;
  showhandcursor: boolean;
  source: string;
  stretches: string;
  subviews: LzView[];
  tintcolor: string;
  totalframes: number;
  unstretchedheight: number;
  unstretchedwidth: number;
  usegetbounds: boolean;
  valign: string;
  visibility: string;
  visible: boolean;
  width: number;
  x: number;
  xoffset: number;
  xscale: number;
  y: number;
  yoffset: number;
  yscale: number;
  onaddsubview: LzDeclaredEvent;
  onbackgroundrepeat: LzDeclaredEvent;
  onblur: LzDeclaredEvent;
  onclick: LzDeclaredEvent;
  onclickable: LzDeclaredEvent;
  onclip: LzDeclaredEvent;
  oncontext: LzDeclaredEvent;
  oncornerradius: LzDeclaredEvent;
  ondblclick: LzDeclaredEvent;
  onerror: LzDeclaredEvent;
  onfocus: LzDeclaredEvent;
  onframe: LzDeclaredEvent;
  onframesloadratio: LzDeclaredEvent;
  onheight: LzDeclaredEvent;
  onkeydown: LzDeclaredEvent;
  onkeyup: LzDeclaredEvent;
  onlastframe: LzDeclaredEvent;
  onload: LzDeclaredEvent;
  onloadratio: LzDeclaredEvent;
  onmousedown: LzDeclaredEvent;
  onmousedragin: LzDeclaredEvent;
  onmousedragout: LzDeclaredEvent;
  onmouseout: LzDeclaredEvent;
  onmouseover: LzDeclaredEvent;
  onmousetrackout: LzDeclaredEvent;
  onmousetrackover: LzDeclaredEvent;
  onmousetrackup: LzDeclaredEvent;
  onmouseup: LzDeclaredEvent;
  onmouseupoutside: LzDeclaredEvent;
  onopacity: LzDeclaredEvent;
  onplay: LzDeclaredEvent;
  onremovesubview: LzDeclaredEvent;
  onshadowangle: LzDeclaredEvent;
  onshadowblurradius: LzDeclaredEvent;
  onshadowcolor: LzDeclaredEvent;
  onshadowdistance: LzDeclaredEvent;
  onstop: LzDeclaredEvent;
  ontimeout: LzDeclaredEvent;
  onvisible: LzDeclaredEvent;
  onwidth: LzDeclaredEvent;
  onx: LzDeclaredEvent;
  ony: LzDeclaredEvent;
  bringToFront(): void;
  sendToBack(): void;
  setSource(source: string, cache?: any, headers?: any, filetype?: any): void;
  static tagname: any;
  static attributes: any;
  _visible: any;
  onresource: any;
  onresourceheight: any;
  onresourcewidth: any;
  onrotation: any;
  ontotalframes: any;
  onunstretchedheight: any;
  onunstretchedwidth: any;
  onvisibility: any;
  onxoffset: any;
  onyoffset: any;
  onfont: any;
  onfontsize: any;
  onfontstyle: any;
  DOUBLE_CLICK_TIME: any;
  onclickregion: any;
  onfgcolor: any;
  sprite: any;
  onbgcolor: any;
  addedToParent: any;
  masked: any;
  _setrescwidth: any;
  _setrescheight: any;
  layouts: any;
  _resource: any;
  oncolortransform: any;
  blurring: any;
  proxyurl: any;
  ontintcolor: any;
  onxscale: any;
  onyscale: any;
  construct(parent?: any, args?: any): any;
  init(): any;
  addSubview(s?: any): any;
  sendAAEvent(childID?: number, eventType?: number, nonHTML?: boolean): any;
  setLayout(layoutobj?: any): any;
  setFontName(val?: any, prop?: any): any;
  searchSubviews(prop?: any, val?: any): any;
  setResource(v?: any): any;
  resourceload(i?: any): any;
  resourceloaderror(e?: any): any;
  resourceloadtimeout(e?: any): any;
  resourceevent(name?: any, value?: any, eventonly?: any, force?: any): any;
  destroy(): any;
  setVisible(v?: any): any;
  setVisibility(amVisible?: any): any;
  setWidth(v?: any): any;
  setHeight(v?: any): any;
  setOpacity(v?: any): any;
  setX(v?: any): any;
  setY(v?: any): any;
  setRotation(v?: any): any;
  setAlign(align?: any): any;
  setXOffset(o?: any): any;
  setYOffset(o?: any): any;
  getBounds(): any;
  setValign(valign?: any): any;
  setColor(c?: any): any;
  getColor(): any;
  setColorTransform(o?: any): any;
  getColorTransform(): any;
  measureSize(axis?: any): any;
  measureWidth(): any;
  measureHeight(): any;
  updateSize(axis?: any, newsize?: any): any;
  updateWidth(newsize?: any): any;
  updateHeight(newsize?: any): any;
  reevaluateSize(ia?: any): any;
  updateResourceSize(): any;
  setAttributeRelative(prop?: string, refView?: LzView): void;
  getAttributeRelative(prop?: string, refView?: LzView): any;
  getLinkage(refView?: any): any;
  mouseevent(eventname?: any): any;
  getMouse(xory?: string): any;
  containsPt(x?: any, y?: any): any;
  getDepthList(): any;
  sendBehind(v?: any): any;
  sendInFrontOf(v?: any): any;
  setResourceNumber(n?: any): any;
  stretchResource(v?: any): any;
  setBGColor(bgc?: any): any;
  unload(): any;
  makeMasked(): any;
  removeMask(): any;
  setClickable(amclickable?: any): any;
  setCursor(cursor?: any): any;
  setPlay(b?: boolean): void;
  getMCRef(): any;
  getDisplayObject(): any;
  play(f?: any, rel?: boolean): void;
  stop(f?: any, rel?: boolean): void;
  setVolume(v?: number): void;
  getVolume(): number;
  setPan(p?: number): void;
  getPan(): number;
  getZ(): any;
  seek(secs?: number): void;
  getCurrentTime(): number;
  getTotalTime(): number;
  getID3(): any;
  setShowHandCursor(s?: any): any;
  setAccessible(accessible?: any): any;
  setAAActive(s?: any): any;
  setAAName(s?: any): any;
  setAADescription(s?: any): any;
  setAATabIndex(s?: any): any;
  setAASilent(s?: any): any;
  shouldYieldFocus(): any;
  getProxyURL(url?: any): any;
  static addProxyPolicy(f?: any): any;
  static removeProxyPolicy(f?: any): any;
  setProxyPolicy(f?: any): any;
  setProxyURL(f?: any): any;
  setContextMenu(cmenu?: any): any;
  getContextMenu(): any;
  getNextSelection(): any;
  getPrevSelection(): any;
  createContext(): any;
  isMouseOver(): any;
  isInFrontOf(sibling?: LzView): any;
  isBehind(sibling?: LzView): any;
  setCSS(stylename?: string, value?: any): any;
}

declare class LzCanvas extends LzView {
  allowfullscreen: boolean;
  appbuilddate: string;
  dataloadtimeout: number;
  datasets: string;
  defaultdataprovider: string;
  embedfonts: boolean;
  framerate: number;
  fullscreen: boolean;
  httpdataprovider: string;
  lpsbuild: string;
  lpsbuilddate: string;
  lpsrelease: string;
  lpsversion: string;
  mediaerrortimeout: number;
  medialoadtimeout: number;
  percentcreated: number;
  proxied: boolean;
  runtime: string;
  scriptlimits: any;
  version: string;
  compileroptions: string;
  debug: boolean;
  title: string;
  id: string;
  history: boolean;
  accessible: boolean;
  onafterinit: LzDeclaredEvent;
  onframerate: LzDeclaredEvent;
  onfullscreen: LzDeclaredEvent;
  onmouseenter: LzDeclaredEvent;
  onmouseleave: LzDeclaredEvent;
  onmousemove: LzDeclaredEvent;
  onpercentcreated: LzDeclaredEvent;
  static tagname: any;
  static attributes: any;
  updatePercentCreatedEnabled: boolean;
  _lzinitialsubviews: any[];
  totalnodes: any;
  creatednodes: any;
  deferInit: any;
  construct(parent?: any, args?: any): any;
  compareVersion(ver?: any, over?: any): any;
  toString(): any;
  initDone(): any;
  init(): any;
  updatePercentCreated(): any;
  initiatorAddNode(e?: any, n?: any): any;
  isProxied(): any;
  setDefaultContextMenu(cmenu?: any): any;
  buildDefaultMenu(): any;
  static versionInfoString(): string;
  LzInstantiateView(e?: any, tn?: any): any;
  lzAddLocalData(name?: any, d?: any, trimwhitespace?: any, nsprefix?: any): any;
}

declare class LzText extends LzView {
  antiAliasType: string;
  direction: string;
  gridFit: string;
  hasdirectionallayout: boolean;
  hscroll: number;
  letterspacing: number;
  lineheight: number;
  maxhscroll: number;
  maxlength: number;
  maxscroll: number;
  multiline: boolean;
  pattern: string;
  resize: boolean;
  scroll: number;
  scrollevents: boolean;
  scrollheight: number;
  scrollwidth: number;
  selectable: boolean;
  sharpness: number;
  text: string;
  textalign: string;
  textdecoration: string;
  textindent: number;
  thickness: number;
  xscroll: number;
  yscroll: number;
  embedfonts: boolean;
  ondirection: LzDeclaredEvent;
  onhscroll: LzDeclaredEvent;
  onlineheight: LzDeclaredEvent;
  onmaxhscroll: LzDeclaredEvent;
  onmaxlength: LzDeclaredEvent;
  onmaxscroll: LzDeclaredEvent;
  onpattern: LzDeclaredEvent;
  onscroll: LzDeclaredEvent;
  onscrollevents: LzDeclaredEvent;
  onscrollheight: LzDeclaredEvent;
  onscrollwidth: LzDeclaredEvent;
  onselectable: LzDeclaredEvent;
  ontext: LzDeclaredEvent;
  ontextlink: LzDeclaredEvent;
  onxscroll: LzDeclaredEvent;
  onyscroll: LzDeclaredEvent;
  static tagname: any;
  static attributes: any;
  tsprite: any;
  static escapeChars: any;
  getDefaultWidth(): any;
  updateAttribute(name?: string, value?: any): void;
  updateLineAttribute(name?: string, value?: any): void;
  scrollevent(name?: string, value?: any): void;
  _updateSize(): any;
  construct(parent?: any, args?: any): any;
  init(): any;
  setResize(val?: any): any;
  addText(t?: any): any;
  clearText(): any;
  setMaxLength(val?: any): any;
  setPattern(val?: any): any;
  getTextWidth(): any;
  getTextHeight(): any;
  applyData(d?: any): any;
  setScroll(h?: any): any;
  getScroll(): any;
  getMaxScroll(): any;
  getBottomScroll(): any;
  setXScroll(n?: any): any;
  setYScroll(n?: any): any;
  setHScroll(s?: any): any;
  annotateAAimg(txt?: any): any;
  parseImgAttributes(attrs?: any, str?: any): any;
  setText(t?: any): any;
  format(control?: string): any;
  addFormat(control?: string): any;
  getText(): any;
  escapeText(ts?: any): any;
  setSelectable(isSel?: any): any;
  setFontSize(fsize?: any): any;
  setFontStyle(fstyle?: any): any;
  setMultiline(ml?: any): any;
  setBorder(onroff?: any): any;
  setWordWrap(wrap?: any): any;
  setEmbedFonts(onroff?: any): any;
  setAntiAliasType(aliasType?: any): any;
  getAntiAliasType(): any;
  setGridFit(gridFit?: any): any;
  getGridFit(): any;
  setSharpness(sharpness?: any): any;
  getSharpness(): any;
  setThickness(thickness?: any): any;
  getThickness(): any;
  setSelection(start?: any, end?: any): any;
  getSelectionPosition(): any;
  getSelectionSize(): any;
  makeTextLink(str?: any, value?: any): any;
  toString(): any;
}

declare class LzInputText extends LzText {
  enabled: boolean;
  password: boolean;
  onenabled: LzDeclaredEvent;
  static tagname: any;
  static attributes: any;
  _onfocusDel: any;
  _onblurDel: any;
  _modemanagerDel: any;
  isprite: any;
  _focused: any;
  _allowselectable: any;
  _selectable: any;
  getDefaultWidth(): any;
  construct(parent?: any, args?: any): any;
  _gotFocusEvent(e?: any): any;
  _gotBlurEvent(e?: any): any;
  inputtextevent(eventname?: string, value?: any): void;
  updateData(): any;
  setEnabled(enabled?: any): any;
  setHTML(htmlp?: any): any;
  getText(): any;
  _modechanged(modalview?: LzView): void;
  _setallowselectable(value?: any): any;
}

type LzAnimatorGroup = LzAnimatorgroup;
type LzContextMenu = LzContextmenu;
type LzContextMenuItem = LzContextmenuitem;

declare class LzBootstrapMessage {
  message: any;
  length: any;
  appendInternal(str?: string, obj?: any): any;
  append(): any;
  charAt(index?: any): any;
  charCodeAt(index?: any): any;
  indexOf(key?: any): any;
  lastIndexOf(key?: any): any;
  toLowerCase(): any;
  toUpperCase(): any;
  toString(): any;
  valueOf(): any;
  concat(): any;
  slice(): string;
  split(): string;
  substr(): string;
  substring(): string;
  toHTML(): any;
  static xmlEscape(input?: any): any;
}

declare class LzFormatCallback {
  callback: (...args: any[]) => any;
  call(): any;
}

declare class LzFormatter {
  static singleEscapeCharacters: any;
  toNumber(s?: any): any;
  pad(value?: any, widthMin?: number, decMax?: any, pad?: string, sign?: string, radix?: number, force?: boolean): any;
  abbreviate(s?: string, l?: any): string;
  stringEscape(s?: string, quoted?: boolean): any;
  formatToString(control?: any): any;
}

declare class LzValueExpr {
}

declare class LzAttributeDescriptor extends LzValueExpr {
  attribute: string;
  type: string;
  value: any;
}

declare class LzInitExpr extends LzAttributeDescriptor {
}

declare class LzOnceExpr extends LzInitExpr {
  methodName: string;
}

declare class LzConstraintExpr extends LzOnceExpr {
}

declare class LzStyleConstraintExpr extends LzConstraintExpr {
  property: string;
  fallback: any;
  warn: boolean;
}

declare class LzAlwaysExpr extends LzConstraintExpr {
  dependenciesName: string;
}

declare class LzStyleExpr extends LzValueExpr {
}

declare class LzStyleAttr extends LzStyleExpr {
  sourceAttributeName: string;
}

declare class LzStyleIdent extends LzStyleExpr {
  sourceValueID: string;
}

declare class LzDeclaredEventClass {
  actual: any;
  ready: boolean;
  sendEvent(eventValue?: any): void;
  clearDelegates(): void;
  removeDelegate(d?: LzDelegate): void;
  getDelegateCount(): number;
  toString(): any;
}

declare class LzCache {
  size: number;
  slots: number;
  destroyable: boolean;
  capacity: number;
  curslot: number;
  data: any[];
  clear(): void;
  ensureSlot(): void;
  put(key?: string, val?: any): any;
  get(key?: string): any;
}

declare class LzStyleAttrBinder extends LzEventable {
  target: LzNode;
  dest: string;
  source: string;
  bind(ignore?: any): any;
}

declare class $lz$class_TypeService {
  PresentationTypes: any;
  static Type: $lz$class_TypeService;
  acceptTypeValue(type?: string, value?: any, node?: LzNode, attribute?: string): any;
  presentTypeValue(type?: string, value?: any, node?: LzNode, attribute?: string): string;
  addType(type?: string, presentationType?: $lz$class_PresentationType): void;
  addTypeAlias(alias?: string, type?: string): void;
}

declare class $lz$class_PresentationType {
  static nullValue: any;
  _dbg_typename: any;
  _dbg_name: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
  present(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_StringPresentationType extends $lz$class_PresentationType {
  static lzxtype: any;
  static nullValue: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_TextPresentationType extends $lz$class_PresentationType {
  static lzxtype: any;
  static nullValue: any;
  static xmlEscapes: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
  present(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_BooleanPresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_NumberPresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_ColorPresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
  present(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_ExpressionPresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_SizePresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lz$class_CSSDeclarationPresentationType extends $lz$class_PresentationType {
  static nullValue: any;
  static lzxtype: any;
  PropRE: any;
  HyphenRE: any;
  CapitalRE: any;
  accept(value?: any, node?: LzNode, attribute?: string): any;
  present(value?: any, node?: LzNode, attribute?: string): any;
}

declare class $lzc$class_userClassPlacement {
}

declare class LzDelegate {
  c: LzEventable;
  m: (...args: any[]) => any;
  hasevents: boolean;
  enabled: boolean;
  event_called: boolean;
  execute(eventValue?: any): any;
  register(eventSender?: any, eventName?: string): void;
  unregisterAll(): void;
  unregisterFrom(event?: LzDeclaredEventClass): void;
  disable(): void;
  enable(): void;
  toString(): any;
  destroy(): void;
}

declare class LzEvent extends LzDeclaredEventClass {
  delegateList: any[];
  locked: boolean;
  addDelegate(d?: LzDelegate): void;
  sendEvent(eventValue?: any): void;
  removeDelegate(d?: LzDelegate): void;
  clearDelegates(): void;
  getDelegateCount(): number;
  toString(): any;
}

declare class LzNotifyingEvent extends LzEvent {
  addDelegate(d?: LzDelegate): void;
  removeDelegate(d?: LzDelegate): void;
  clearDelegates(): void;
  notify(ready?: boolean): void;
}

declare class LzKernelUtils {
  static CSSDimension(value?: any, units?: string): any;
  static range(val?: any, max?: any, min?: any): any;
  static rect(context?: any, x?: any, y?: any, width?: any, height?: any, topleftradius?: any, toprightradius?: any, bottomrightradius?: any, bottomleftradius?: any): any;
  static parselzoptions(lzopts?: string): any;
}

declare class LzLibraryCleanup extends LzNode {
  static attributes: any;
  lib: any;
}

declare class LzBrowserKernel {
  static loadURL(url?: any, target?: any, features?: any): any;
  static loadJS(js?: any, target?: any): any;
  static callJS(methodname?: any, callback?: any): any;
  static setHistory(n?: any): any;
  static callMethod(js?: any): any;
  static getVersion(): any;
  static getOS(): any;
  static getLoadURL(): any;
  static getInitArg(name?: any): any;
  static getLzOption(name?: any): any;
  static getAppID(): any;
  static isAAActive(): any;
}

declare class LzLibrary extends LzNode {
  static tagname: any;
  static attributes: any;
  loaded: any;
  loading: any;
  sprite: any;
  href: any;
  stage: any;
  onload: any;
  static libraries: any;
  construct(parent?: any, args?: any): any;
  init(): any;
  destroy(): any;
  static findLibrary(libname?: any): any;
  toString(): any;
  load(): any;
  loadfinished(): any;
  static stripQueryString(str?: string): string;
}

declare class LzContextMenuKernel {
  owner: LzContextMenu;
  showbuiltins: any;
  _delegate: any;
  static lzcontextmenu: any;
  setDelegate(delegate?: any): any;
  addItem(item?: any): any;
  hideBuiltInItems(): any;
  showBuiltInItems(): any;
  clearItems(): any;
}

declare class LzContextMenuItemKernel {
  owner: LzContextMenuItem;
  cmenuitem: any;
  _delegate: any;
  setDelegate(delegate?: any): any;
  setCaption(caption?: any): any;
  getCaption(): any;
  setEnabled(val?: any): any;
  setSeparatorBefore(val?: any): any;
  setVisible(val?: any): any;
}

declare class LzTextscrollEvent extends LzNotifyingEvent {
  static LzDeclaredTextscrollEvent: LzDeclaredEventClass;
  notify(ready?: boolean): void;
}

declare class LzTextlinkEvent extends LzNotifyingEvent {
  static LzDeclaredTextlinkEvent: LzDeclaredEventClass;
  notify(ready?: boolean): void;
}

declare class LzViewLinkage {
  xscale: number;
  yscale: number;
  xoffset: number;
  yoffset: number;
  uplinkArray: any[];
  downlinkArray: any[];
  update(xory?: string): any;
}

declare class LzScript extends LzNode {
  static tagname: any;
  static attributes: any;
  src: string;
}

declare class LzFont {
  style: any;
  name: any;
  height: any;
  ascent: any;
  descent: any;
  advancetable: any;
  lsbtable: any;
  rsbtable: any;
  fontobject: any;
  leading: any;
  toString(): any;
}

declare class LzURL {
  protocol: string;
  host: string;
  port: string;
  path: string;
  file: string;
  query: string;
  fragment: string;
  _parsed: string;
  parseURL(url?: string): void;
  _splitPath(pathfile?: string): void;
  dupe(): LzURL;
  toString(): string;
  static merge(url?: LzURL, defaults?: LzURL): LzURL;
}

declare class LzDataNodeMixin {
  onownerDocument: LzDeclaredEventClass;
  onDocumentChange: LzDeclaredEventClass;
  onparentNode: LzDeclaredEventClass;
  onchildNode: LzDeclaredEventClass;
  onchildNodes: LzDeclaredEventClass;
  onattributes: LzDeclaredEventClass;
  onnodeName: LzDeclaredEventClass;
  nodeType: number;
  parentNode: any;
  ownerDocument: LzDataElementMixin;
  childNodes: any[];
  sel: boolean;
  getParent(): any;
  getOffset(): number;
  getPreviousSibling(): any;
  getNextSibling(): any;
  childOfNode(el?: any, allowself?: boolean): boolean;
  childOf(el?: any, allowself?: any): any;
  setOwnerDocument(ownerDoc?: any): void;
  cloneNode(deep?: boolean): any;
  serialize(): string;
  setUserData(key?: string, data?: any, handler?: any): any;
  getUserData(key?: string): any;
}

declare class LzDataNode extends LzEventable {
  static ELEMENT_NODE: number;
  static TEXT_NODE: number;
  static DOCUMENT_NODE: number;
  static stringToLzData(str?: string, trimwhitespace?: boolean, nsprefix?: boolean): LzDataElement;
  toString(): any;
}

declare class LzDataElementMixin {
  nodeName: string;
  attributes: any;
  insertBefore(newChild?: any, refChild?: any): any;
  replaceChild(newChild?: any, oldChild?: any): any;
  removeChild(oldChild?: any): any;
  appendChild(newChild?: any): any;
  hasChildNodes(): boolean;
  cloneNode(deep?: boolean): any;
  getAttr(name?: string): string;
  setAttr(name?: string, value?: string): string;
  removeAttr(name?: string): string;
  hasAttr(name?: string): boolean;
  getFirstChild(): any;
  getLastChild(): any;
  setAttrs(attrs?: any): void;
  setChildNodes(children?: any[]): void;
  setNodeName(name?: string): void;
  getElementsByTagName(name?: string): any[];
  serialize(): string;
  serializeInternal(len?: number): string;
  handleDocumentChange(what?: string, who?: any, type?: number, cobj?: any): void;
  toString(): any;
}

declare class LzDataElement extends LzDataNode {
  static NODE_CLONED: number;
  static NODE_IMPORTED: number;
  static NODE_DELETED: number;
  static NODE_RENAMED: number;
  static NODE_ADOPTED: number;
  static ELEMENT_NODE: number;
  static TEXT_NODE: number;
  static DOCUMENT_NODE: number;
  static whitespaceChars: any;
  static makeNodeList(count?: number, name?: string): any[];
  static valueToElement(o?: any): LzDataElement;
  static stringToLzData(str?: string, trimwhitespace?: boolean, nsprefix?: boolean): LzDataElement;
  static trim(str?: string): string;
}

declare class LzDataText extends LzDataNode {
  ondata: LzDeclaredEventClass;
  nodeName: string;
  data: string;
  setData(newdata?: string): any;
  cloneNode(deep?: boolean): any;
  serialize(): string;
  toString(): any;
}

declare class LzDataRequest extends LzEventable {
  static SUCCESS: string;
  static TIMEOUT: string;
  static ERROR: string;
  static READY: string;
  static LOADING: string;
  requestor: any;
  src: string;
  timeout: number;
  status: string;
  rawdata: string;
  error: string;
  onstatus: LzDeclaredEventClass;
}

declare class LzDataProvider extends LzEventable {
  doRequest(dreq?: LzDataRequest): void;
  abortLoadForRequest(dreq?: LzDataRequest): void;
}

declare class LzHTTPDataRequest extends LzDataRequest {
  method: string;
  postbody: string;
  proxied: boolean;
  proxyurl: string;
  multirequest: boolean;
  queuerequests: boolean;
  queryparams: LzParam;
  requestheaders: LzParam;
  getresponseheaders: boolean;
  responseheaders: LzParam;
  cacheable: boolean;
  clientcacheable: boolean;
  trimwhitespace: boolean;
  nsprefix: boolean;
  serverproxyargs: any;
  xmldata: LzDataElement;
  loadtime: number;
  loadstarttime: number;
  secure: boolean;
  secureport: number;
  parsexml: boolean;
  loader: any;
}

declare class LzHTTPDataProvider extends LzDataProvider {
  makeLoader(dreq?: LzHTTPDataRequest): any;
  abortLoadForRequest(dreq?: LzDataRequest): void;
  doRequest(dreq?: LzDataRequest): void;
  loadSuccess(loader?: any, data?: any): void;
  loadError(loader?: any, data?: any): void;
  loadTimeout(loader?: any, data?: any): void;
  setRequestError(dreq?: LzHTTPDataRequest, msg?: string): void;
  loadResponse(dreq?: LzHTTPDataRequest, data?: any): void;
  destroy(): any;
}

declare class __LzHttpDatasetPoolClass {
  _uid: number;
  _p: any[];
  get(dataDel?: LzDelegate, errorDel?: LzDelegate, timeoutDel?: LzDelegate, acceptenc?: boolean): LzDataset;
  recycle(dset?: LzDataset): void;
}

declare class LzParam extends LzEventable {
  d: any;
  delimiter: string;
  separator: string;
  static parseQueryString(query?: string): any;
  addObject(o?: any): void;
  clone(arg?: any): LzParam;
  remove(name?: string): void;
  setValue(name?: string, val?: string, enc?: boolean): void;
  addValue(name?: string, val?: string, enc?: boolean): void;
  getValue(name?: string): string;
  getValues(name?: string): any[];
  getValueNoCase(name?: string): any;
  getNames(): any[];
  setDelimiter(d?: string): string;
  setSeparator(s?: string): string;
  toString(): string;
  serialize(sep?: string, delim?: string, uriencode?: boolean): string;
}

declare class LzParsedPath {
  path: string;
  selectors: any[];
  context: any;
  dsetname: string;
  dsrcname: string;
  islocaldata: any[];
  operator: string;
  aggOperator: string;
  hasAttrOper: boolean;
  hasOpSelector: boolean;
  hasDotDot: boolean;
  getContext(dp?: LzDatapointer): any;
  static trim(s?: string): string;
  toString(): any;
  debugWrite(): any;
}

declare class AnonDatasetGenerator extends LzEventable {
  pp: LzParsedPath;
  onDocumentChange: LzDeclaredEventClass;
  onerror: LzDeclaredEventClass;
  ontimeout: LzDeclaredEventClass;
  noncontext: boolean;
  getContext(): any;
  getDataset(): any;
}

declare class LzReplicationManager extends LzDatapath {
  asyncnew: boolean;
  initialnodes: any[];
  clonePool: any[];
  cloneClass: any;
  cloneParent: LzNode;
  cloneAttrs: any;
  cloneChildren: any[];
  hasdata: boolean;
  orderpath: string;
  comparator: (...args: any[]) => any;
  visible: boolean;
  nodes: any[];
  clones: any[];
  onnodes: LzDeclaredEventClass;
  onclones: LzDeclaredEventClass;
  onvisible: LzDeclaredEventClass;
  getDefaultPooling(): boolean;
  construct(odp?: any, args?: any): any;
  setDataContext(p?: any, implicit?: boolean): void;
  getCloneNumber(n?: number): LzNode;
  mergesort(arr?: any[], lo?: number, hi?: number): any[];
  orderf(a?: any, b?: any): number;
  ascDict(a?: string, b?: string): number;
  descDict(a?: string, b?: string): number;
  setOrder(xpath?: string, comparator?: any): void;
  setComparator(comparator?: any): void;
  getNewClone(forceNew?: any): LzNode;
  poolClone(): void;
  destroyClone(v?: LzNode): void;
  setXPath(xp?: string): boolean;
  handleDeletedNode(c?: number): void;
  getCloneForNode(p?: LzDataElement, dontmake?: boolean): LzNode;
  toString(): any;
  setVisible(vis?: boolean): void;
  getContext(chgpkg?: any): any;
  detachClone(cl?: LzView): void;
  reattachClone(cl?: LzView): LzView;
  updateData(): any;
}

declare class LzRefNode extends LzNode {
  xpath: string;
}

declare class LzDataAttrBind extends LzDatapointer {
  setAttr: string;
  pathparent: LzDatapath;
  node: LzNode;
  type: string;
  destroy(): any;
  setDataContext(dc?: any, implicit?: boolean): void;
  updateData(): any;
  runXPath(): boolean;
  toString(): any;
}

declare class LzLazyReplicationManager extends LzReplicationManager {
  sizeAxis: string;
  cloneimmediateparent: LzView;
  updateDel: LzDelegate;
  viewsize: number;
  totalsize: number;
  mask: LzView;
  getDefaultPooling(): boolean;
  construct(odp?: any, args?: any): any;
  toString(): any;
  getCloneForNode(p?: LzDataElement, dontmake?: boolean): LzNode;
  getCloneNumber(n?: number): LzNode;
}

declare class LzResizeReplicationManager extends LzLazyReplicationManager {
  datasizevar: string;
  getDefaultPooling(): boolean;
  construct(odp?: any, args?: any): any;
  getPositionByNode(n?: any): number;
}

declare class LzColorUtils {
  static stringToColor(s?: any): any;
  static fromrgb(s?: string): any;
  static dectohex(n?: any, padding?: number): any;
  static torgb(s?: any): any;
  static tohsv(rgb?: any): any;
  static fromhsv(h?: any, s?: any, v?: any): any;
  static convertColor(s?: any): any;
  static hextoint(s?: any): any;
  static inttohex(n?: any, padding?: number): any;
  static inttocolorobj(val?: any): any;
  static rgbatoint(r?: number, g?: number, b?: number, a?: any): number;
  static inttorgba(rgb?: number): any[];
  static findalpha(rgba?: any): any;
  static applyTransform(color?: any, trans?: any): any;
}

declare class LzUtilsClass {
  color: any;
  colornames: any;
  hextoint(s?: any): any;
  inttohex(n?: any, padding?: number): any;
  dectohex(n?: any, padding?: number): any;
  stringToColor(s?: any): any;
  torgb(s?: any): any;
  fromrgb(s?: string): any;
  safeEval(js?: string): any;
  safeNew(js?: string): any;
}

declare class LzInstantiatorService extends LzEventable {
  checkQDel: LzDelegate;
  static LzInstantiator: LzInstantiatorService;
  halted: boolean;
  isimmediate: boolean;
  isdatareplicating: boolean;
  istrickling: boolean;
  isUpdating: boolean;
  safe: boolean;
  timeout: number;
  makeQ: any[];
  trickleQ: any[];
  tricklingQ: any[];
  datareplQ: any[];
  dataQ: any[];
  syncNew: boolean;
  trickletime: number;
  setSafeInstantiation(isSafe?: boolean): void;
  requestInstantiation(v?: LzNode, children?: any[]): void;
  enableDataReplicationQueuing(rman?: any): void;
  clearDataReplicationQueue(rman?: any): void;
  newReverseArray(arr?: any): any[];
  checkUpdate(): void;
  checkQ(ignoreme?: any): void;
  makeSomeViews(cq?: any[], otime?: number): number;
  trickleInstantiate(v?: LzNode, children?: any[]): void;
  createImmediate(v?: LzNode, children?: any[]): void;
  completeTrickle(v?: LzNode): void;
  halt(): void;
  resume(): void;
  drainQ(limit?: number): boolean;
}

declare class LzGlobalMouseService extends LzEventable {
  static LzGlobalMouse: LzGlobalMouseService;
  onmousemove: LzDeclaredEventClass;
  onmouseup: LzDeclaredEventClass;
  onmouseupoutside: LzDeclaredEventClass;
  onmouseover: LzDeclaredEventClass;
  onmouseout: LzDeclaredEventClass;
  onmousedown: LzDeclaredEventClass;
  onmousedragin: LzDeclaredEventClass;
  onmousedragout: LzDeclaredEventClass;
  onmouseleave: LzDeclaredEventClass;
  onmouseenter: LzDeclaredEventClass;
  onmouseevent: LzDeclaredEventClass;
  onclick: LzDeclaredEventClass;
  ondblclick: LzDeclaredEventClass;
}

declare class LzBrowserService {
  capabilities: any;
  static LzBrowser: LzBrowserService;
  static sOptionNameMap: any;
  postToLps: boolean;
  parsedloadurl: LzURL;
  defaultPortNums: any;
  loadURL(url?: string, target?: string, features?: string): void;
  loadJS(js?: string, target?: string): void;
  callJS(methodname?: string, callback?: any, args?: any): any;
  getVersion(): string;
  getOS(): string;
  getLoadURL(): string;
  getURL(): string;
  getInitArg(name?: string): any;
  oldOptionName(key?: string): any;
  getLzOption(name?: string): any;
  getAppID(): string;
  showMenu(truefalse?: boolean): void;
  setClipboard(str?: string): void;
  setWindowTitle(str?: string): void;
  isAAActive(): boolean;
  updateAccessibility(): void;
  loadProxyPolicy(url?: string): void;
  getBaseURL(secure?: any, port?: any): LzURL;
  getLoadURLAsLzURL(): LzURL;
  toAbsoluteURL(url?: string, secure?: boolean): string;
  xmlEscape(str?: string): string;
  urlEscape(str?: string): string;
  urlUnescape(str?: string): string;
  usePost(): boolean;
  supportsPost(): boolean;
  makeProxiedURL(params?: any): string;
}

declare class LzModeManagerService extends LzEventable {
  onmode: LzDeclaredEventClass;
  willCall: boolean;
  eventsLocked: boolean;
  modeArray: any[];
  remotedebug: any;
  static LzModeManager: LzModeManagerService;
  makeModal(view?: LzView): void;
  release(view?: LzView): void;
  releaseAll(): void;
  handleMouseEvent(view?: LzView, eventStr?: string): void;
  globalLockMouseEvents(): void;
  globalUnlockMouseEvents(): void;
  hasMode(view?: LzView): boolean;
  getModalView(): LzView;
  rawMouseEvent(eventname?: string, view?: LzView): void;
}

declare class LzCursorService extends LzEventable {
  static LzCursor: LzCursorService;
  showHandCursor(show?: boolean): void;
  setCursorGlobal(resource?: string): void;
  lock(): void;
  unlock(): void;
  restoreCursor(): void;
}

declare class LzKeysService extends LzEventable {
  static LzKeys: LzKeysService;
  downKeysHash: any;
  downKeysArray: any[];
  keycombos: any;
  onkeydown: LzDeclaredEventClass;
  onkeyup: LzDeclaredEventClass;
  onmousewheeldelta: LzDeclaredEventClass;
  onkeyevent: LzDeclaredEventClass;
  codemap: any;
  ctrlKey: boolean;
  mousewheeldelta: number;
  keyCodes: any;
  gotKeyDown(kC?: number, info?: string): void;
  gotKeyUp(kC?: number): void;
  isKeyDown(k?: any): boolean;
  callOnKeyCombo(d?: any, kCArr?: any[]): void;
  removeKeyComboCall(d?: any, kCArr?: any[]): any;
  enableEnter(onroff?: boolean): void;
  gotLastFocus(ignore?: any): void;
  setGlobalFocusTrap(istrapped?: boolean): void;
}

declare class LzAudioService {
  capabilities: any;
  static LzAudio: LzAudioService;
  playSound(snd?: string): void;
  stopSound(): void;
  startSound(): void;
  getVolume(): number;
  setVolume(v?: number): void;
  getPan(): number;
  setPan(p?: number): void;
}

declare class LzHistoryService extends LzEventable {
  static LzHistory: LzHistoryService;
  isReady: boolean;
  ready: boolean;
  onready: LzDeclaredEventClass;
  persist: boolean;
  _persistso: any;
  offset: number;
  capabilities: any;
  onoffset: LzDeclaredEventClass;
  receiveHistory(o?: any): number;
  receiveEvent(n?: string, v?: any): void;
  getCanvasAttribute(n?: string): any;
  setCanvasAttribute(n?: string, v?: any): void;
  callMethod(js?: string): any;
  save(who?: any, prop?: string, val?: any): void;
  commit(): void;
  move(by?: number): void;
  next(): void;
  prev(): void;
  clear(): void;
  setPersist(p?: boolean): void;
}

declare class LzTrackService extends LzEventable {
  static LzTrack: LzTrackService;
  register(v?: LzView, group?: string): void;
  unregister(v?: LzView, group?: string): void;
  activate(group?: string): void;
  deactivate(group?: string): void;
}

declare class LzIdleEvent extends LzNotifyingEvent {
  notify(ready?: boolean): void;
}

declare class LzIdleService extends LzEventable {
  coi: any[];
  regNext: boolean;
  removeCOI: LzDelegate;
  onidle: LzDeclaredEventClass;
  static LzIdle: LzIdleService;
  callOnIdle(d?: LzDelegate): void;
  removeCallIdleDelegates(t?: any): void;
  setFrameRate(fps?: number): void;
}

declare class LzCSSStyleRule {
  parsed: any;
  specificity: number;
  properties: any;
  _lexorder: any;
  _dbg_name: any;
  equal(that?: any): boolean;
}

declare class LzCSSStyleDependencies {
  count: number;
  deps: any;
  gather(node?: LzNode, attr?: string): void;
}

declare class LzCSSStyleClass {
  _rules: any[];
  _attrRules: any;
  _idRules: any;
  _tagRules: any;
  _rulenum: number;
  _lastSort: number;
  getComputedStyle(node?: any): any;
  getPropertyValueFor(node?: LzNode, pname?: string): any;
  getPropertyCache(node?: LzNode): any;
  getRulesCache(node?: LzNode): any[];
  _printRuleArray(arr?: any): any;
  _compoundSelectorApplies(parsedsel?: any[], startnode?: LzNode, deps?: LzCSSStyleDependencies): boolean;
  _sortRules(): void;
  _addRule(r?: LzCSSStyleRule): void;
}

declare class LzCSSStyleDeclaration {
  _node: any;
  getPropertyValue(pname?: any): any;
  setNode(node?: any): any;
}

declare class LzStyleSheet {
  type: any;
  disabled: any;
  ownerNode: any;
  parentStyleSheet: any;
  href: any;
  title: any;
  media: any;
}

declare class LzCSSStyleSheet extends LzStyleSheet {
  ownerRule: any;
  cssRules: any;
  insertRule(rule?: any, index?: any): any;
}

declare class LzFocusService extends LzEventable {
  onfocus: LzDeclaredEventClass;
  onescapefocus: LzDeclaredEventClass;
  lastfocus: LzView;
  csel: LzView;
  cseldest: LzView;
  static LzFocus: LzFocusService;
  upDel: LzDelegate;
  downDel: LzDelegate;
  lastfocusDel: LzDelegate;
  focuswithkey: boolean;
  gotKeyUp(kC?: any): void;
  gotKeyDown(kC?: any): void;
  setFocus(newsel?: LzView, fwkey?: any): void;
  clearFocus(): void;
  getFocus(): LzView;
  next(): void;
  prev(): void;
  getNext(focusview?: LzView): LzView;
  getPrev(focusview?: LzView): LzView;
  genMoveSelection(movedir?: number): void;
  accumulateSubviews(accum?: any[], v?: LzView, includep?: LzView, top?: boolean): void;
  moveSelSubview(v?: LzView, mvdir?: number, sendEsc?: boolean): LzView;
}

declare class LzTimerService {
  timerList: any;
  static LzTimer: LzTimerService;
  execDelegate: (...args: any[]) => any;
  removeTimerWithID(d?: LzDelegate, id?: number): void;
  addTimer(d?: LzDelegate, millisecs?: number): number;
  removeTimer(d?: LzDelegate): any;
  resetTimer(d?: LzDelegate, millisecs?: number): number;
}

declare class $lzc$class_lzcontextmenuseparator extends LzView {
  static tagname: any;
  static attributes: any;
  redraw(context_$a?: any): any;
}

declare class $lzc$class_lzcontextmenutext extends LzText {
  static tagname: any;
  static attributes: any;
  redraw(context_$a?: any): any;
}

declare class $lzc$class_lzcontextmenudisabled extends LzText {
  static tagname: any;
  static attributes: any;
}

declare class $lzc$class_ii6lntc extends LzView {
  static displayName: any;
  static attributes: any;
  redraw(context_$a?: any): any;
}

declare class $lzc$class_lzcontextmenu extends LzView {
  static tagname: any;
  static children: any;
  static attributes: any;
  inset: any;
  background: any;
  container: any;
  select(offset_$a?: any): any;
  show(): any;
  hide(): any;
  setItems(newitems_$a?: any): any;
  registerRedraw(who_$a?: any): any;
  unregisterRedraw(who_$a?: any): any;
}

declare const lz: {
  Formatter: typeof LzFormatter;
  DeclaredEventClass: typeof LzDeclaredEventClass;
  Eventable: typeof LzEventable;
  TypeService: typeof $lz$class_TypeService;
  Type: any;
  Delegate: typeof LzDelegate;
  Event: typeof LzEvent;
  NotifyingEvent: typeof LzNotifyingEvent;
  Font: typeof LzFont;
  URL: typeof LzURL;
  DataNodeMixin: typeof LzDataNodeMixin;
  DataNode: typeof LzDataNode;
  DataElementMixin: typeof LzDataElementMixin;
  DataElement: typeof LzDataElement;
  DataText: typeof LzDataText;
  DataRequest: typeof LzDataRequest;
  DataProvider: typeof LzDataProvider;
  HTTPDataRequest: typeof LzHTTPDataRequest;
  HTTPDataProvider: typeof LzHTTPDataProvider;
  Param: typeof LzParam;
  ReplicationManager: typeof LzReplicationManager;
  LazyReplicationManager: typeof LzLazyReplicationManager;
  ResizeReplicationManager: typeof LzResizeReplicationManager;
  ColorUtils: typeof LzColorUtils;
  Instantiator: LzInstantiatorService;
  GlobalMouseService: typeof LzGlobalMouseService;
  GlobalMouse: LzGlobalMouseService;
  BrowserService: typeof LzBrowserService;
  Browser: LzBrowserService;
  ModeManagerService: typeof LzModeManagerService;
  ModeManager: LzModeManagerService;
  CursorService: typeof LzCursorService;
  Cursor: LzCursorService;
  KeysService: typeof LzKeysService;
  Keys: LzKeysService;
  AudioService: typeof LzAudioService;
  Audio: LzAudioService;
  HistoryService: typeof LzHistoryService;
  History: LzHistoryService;
  TrackService: typeof LzTrackService;
  Track: LzTrackService;
  IdleService: typeof LzIdleService;
  Idle: LzIdleService;
  CSSStyleRule: typeof LzCSSStyleRule;
  CSSStyle: typeof LzCSSStyleClass;
  CSSStyleDeclaration: typeof LzCSSStyleDeclaration;
  CSSStyleSheet: typeof LzCSSStyleSheet;
  FocusService: typeof LzFocusService;
  Focus: LzFocusService;
  TimerService: typeof LzTimerService;
  Timer: LzTimerService;
  [k: string]: any;
};
declare const canvas: LzCanvas;
declare const Debug: any;
declare var $debug: boolean;
